### ISSUE TITLE
Problema ao enviar simples mensagem de texto

### ISSUE THREAD

**Issue by joweste** [mikelustosa/Projeto-TInject#1]
Boa noite, na rotina abaixo, o botãoo enviar mensagem de texto, parece ter um problema no noi. do telefone.
Na linha
` InjectWhatsapp1.send(ed_num.Text, mem_message.Text);`
se eu ponho um telefone como 5521984370088, a mensagem nunca chega, apesar do dialogo de enviado ser mostrado. 
Para ser enviado eu preciso acrescentar "@c.us" ao no. do telefone.

É assim mesmo?

```
procedure TfrmPrincipal.btEnviaTextoClick(Sender: TObject);
begin
  if (not Assigned(frm_servicesWhats)) or (Assigned(frm_servicesWhats) and (frm_servicesWhats.vAuth = false)) then
  begin
    application.MessageBox('Você não está autenticado.','TInject', mb_iconwarning + mb_ok);
    abort;
  end;

  InjectWhatsapp1.send(ed_num.Text, mem_message.Text);
  application.MessageBox('Mensagem enviada com sucesso!','TInject', mb_iconAsterisk + mb_ok);
end;

```

**Comment by Dorpoa** [comment]
Ola..
Está certo.. porem os numeros de Whats sao de 8 digito. Nao tem o 9º digito..

Recomendo vc manter sempre a ultima versao do repositorio, pois esta em constante atualizaçao

**Comment by joweste** [comment]
Pra mim so funcionou com nove digitos. Estou com a ultima atualização.
essa função: function TAjustNumber.Format(PNum: String): String;
só formatou corretamente quando eu defini LengthPhone=9
