### ISSUE TITLE
queryLinkPreview Function not found

### ISSUE THREAD

**Issue by luidiva** [mikelustosa/Projeto-TInject#16]
Parece que foi retirada a função Store.WapQuery.queryLinkPreview() que trazia informações sobre a página de um link enviado na mensagem, que é utilizado para preencher os atributos de linkPreview:

window.WAPI.sendLinkWithAutoPreview = async function (chatId, url, text) {
    var chatSend = WAPI.getChat(chatId);
    if (chatSend === undefined) {
        return false;
    }
    const linkPreview = await Store.WapQuery.**queryLinkPreview**(url);
    return (await chatSend.sendMessage(text.includes(url) ? text : '${url}\n${text}, {
            linkPreview
        })) == 'success'
}

**Comment by mikelustosa** [comment]
Resolvido na versão Corporate.
