### ISSUE TITLE
Did you know why addAndSendMsgToChat stops working 

### ISSUE THREAD

**Issue by vega-7** [mikelustosa/Projeto-TInject#19]
Im trying to send a vcard , this in the past works flawless , right now , its not, also i tried sending a location in both cases nothing happend.? the worst thing is that the function doesnt throw any error or something.  well yes using this 

await  Promise.all(window.Store.addAndSendMsgToChat(chat, tempMsg ));Uncaught (in promise)
im getting this error: TypeError: h.waitForPrep is not a function, 

but removing the promise.all function im not getting any error or response or result. 

I tried with @Parth Thakkar solution a guy in a whatsapp forum 
{ id: "addAndSendMsgToChat", conditions: (module) => (module.addAndSendMsgToChat && module.resendMsgToChat) ? module.addAndSendMsgToChat : null } but doesnt work either.

- - - - - - - - - - -

Theres any fix to this or whatsapp removed this or we have to wait an update? or the user has to activate any options related to privacy or something

Can anyone help with this, i dont know what to do here.

Thanks

**Comment by Parth** [comment]
You have tagged the wrong @parth

**Comment by mikelustosa** [comment]
FIX in Corpotate version
