### ISSUE TITLE
window.WAPI.sendMessageToID no work

### ISSUE THREAD

**Issue by mj0912** [mikelustosa/Projeto-TInject#21]
hi 
window.WAPI.sendMessageToID no work from 3 day ago.
before can send message to unknown whatsapp id,
but now only send message to chat list!

how way for send message  to all whatsapp users?

**Comment by leonelvila** [comment]
> hi
> window.WAPI.sendMessageToID no work from 3 day ago.
> before can send message to unknown whatsapp id,
> but now only send message to chat list!
> 
> how way for send message to all whatsapp users?

hi,
I have the same problem.
any solution for this?

**Comment by mikelustosa** [comment]
FIX in Corportate version.
