### ISSUE TITLE
WhatsApp web 2.2142.11

### ISSUE THREAD

**Issue by alpires** [mikelustosa/Projeto-TInject#27]
O componente parou de funcionar na versão 2.2142.11 do whatsapp web.

**Comment by joaocarlosautobyte** [comment]
Pessoal, tive que refazer todos os procedimentos, de novo.
Será que de agora em diante, vou precisar fazer sempre esse procedimento de limpeza, sempre que eu for conectar de novo?
Preciso saber para colocar dentro da minha aplicação...

**Comment by joaocarlosautobyte** [comment]
Se tiver algum comando, que eu possa usar para automaticamente apagar os caches, agradeço.
ai, o JS eu mesmo apago na aplicação....
