### ISSUE TITLE
TInject dispara evento de receber mensagem ao baixar mensagens antigas

### ISSUE THREAD

**Issue by leoguitar2006** [mikelustosa/Projeto-TInject#39]
Com a atualização do WhatsApp Web para trabalhar offline, as mensagens estão sendo baixadas para o computador. Quando mensagens antigas são baixadas, o TInject intepreta elas como recebidas no momento.

Existe alguma solução para isso ?

**Comment by mikelustosa** [comment]
Basta você tratar o id da mensagem, ou simplesmente deletar o chat para novas conversas.
