### ISSUE TITLE
av ao compilar

### ISSUE THREAD

**Issue by engenheirodiegocosta** [mikelustosa/Projeto-TInject#4]
amigos ao compilar eu tomo av dentro da classe do indy. o que poderia ser?

**Comment by Dorpoa** [comment]
Olá!
Para resolver esse problema, destrua a herança do componente Indy.
Para solucionar. Retire o inherited e ajuste o Crete do Indy conforme manda sua versão do Delphi.

Exemplo 
   Xxxx := TIndy.create
Ou
   Xxxx := TIndy.create(nil)

Obs. O exemplo acima e simbólico e apenas para facilitar a interpretação.

**Comment by engenheirodiegocosta** [comment]
> Olá!
> Para resolver esse problema, destrua a herança do componente Indy.
> Para solucionar. Retire o inherited e ajuste o Crete do Indy conforme manda sua versão do Delphi.
> 
> Exemplo
> Xxxx := TIndy.create
> Ou
> Xxxx := TIndy.create(nil)
> 
> Obs. O exemplo acima e simbólico e apenas para facilitar a interpretação.

em qual classe devo fazer o ajuste? ajustei na do collection dpk e continua o problema.
teria alguma versão funcional no delphi rio?

att

**Comment by Dorpoa** [comment]
Não sei de cabeça mas procure pelo Indy

**Comment by engenheirodiegocosta** [comment]
Resolvido, tive que deixar o inherited create que está com ifdef version 23 e comentar os outros.
no Delphi Rio é necessário.
Agradeço pelo feed.

**Comment by leonamjlima** [comment]
Pessoal, seguindo a video aula, quando declaro essas duas units: uBotGestor, uBotConversa.

Não compila, diz que não está encontrando essas duas units, e eu não estou conseguindo localizar nas pastas do componente, algm pode me ajudar?

**Comment by sidsanches** [comment]
> Pessoal, seguindo a video aula, quando declaro essas duas units: uBotGestor, uBotConversa.
> 
> Não compila, diz que não está encontrando essas duas units, e eu não estou conseguindo localizar nas pastas do componente, algm pode me ajudar?

Estou com o mesmo problema.
Alguém faz idéia de como resolver?
