### ISSUE TITLE
Getting Error in checkNumberStatus function

### ISSUE THREAD

**Issue by rajeshshettysrs** [mikelustosa/Projeto-TInject#41]
Dear sir,Getting error while executing above function.Please verify once

Error is,
The HTTP request to the remote WebDriver server for URL http://localhost:54648/session/09f510b1173aacffa3b7dd15fc26f020/execute/sync timed out after 60 seconds.

**Comment by leonelvila** [comment]
I fixed this way:

Replace the module condition:
{ id: "WapQueryMD", conditions: (module) => (module.queryExists **&& module.queryPhoneExists**) ? module : null },

then, replace the query function in the checkNumberStatus:
result = await window.Store.WapQueryMD.**queryPhoneExists**('+'+id);

hope it helps!

**Comment by rajeshshettysrs** [comment]
> I fixed this way:
> 
> Replace the module condition: { id: "WapQueryMD", conditions: (module) => (module.queryExists **&& module.queryPhoneExists**) ? module : null },
> 
> then, replace the query function in the checkNumberStatus: result = await window.Store.WapQueryMD.**queryPhoneExists**('+'+id);
> 
> hope it helps!

Thank you very much sir,Its working :-)

**Comment by rajeshshettysrs** [comment]
solution give by [leonelvila] sir is worked

**Comment by IrfanIrfan644** [comment]
> 

im trying to call this function but getting error 'can not read the property of queryPhoneExists' while i had included the header module like ' { id: "WapQueryMD", conditions: (module) => (module.queryExists && module.queryPhoneExists) ? module : null }'
im stuck here..
can you please guide me..
thanks

**Comment by rajeshshettysrs** [comment]
Not working sir,For invalid numbers also getting true sir,Is their any other way to check valid/invalid whatsapp number plz help?
