### ISSUE TITLE
Send Buttons

### ISSUE THREAD

**Issue by Zer0bytte** [mikelustosa/Projeto-TInject#46]
How can i send buttons like this??
![73892179-f13d4a80-4854-11ea-80b3-8723d7df3290](https://user-images.githubusercontent.com/85482481/193451565-7a80f503-7b72-46ec-b3a5-27ef980120da.png)
Im using SendButtons Function give me this error 
![image](https://user-images.githubusercontent.com/85482481/193451657-8bf78b00-d47b-4dd1-9151-031962ec1bea.png)

**Comment by mikelustosa** [comment]
Função disponível por enquanto somente na versão Corporate.
