### ISSUE TITLE
Depois de um tempo para de enviar mensagem

### ISSUE THREAD

**Issue by rodrigo-ogioni** [mikelustosa/Projeto-TInject#47]
Quando se passa algumas horas o sistema para de enviar mensagens. Então tem que reiniciar todo o sistema e reconectar novamente ao whatsapp. Passa mais um tempo e tem que refazer esse processo.
Alguma dica?

**Comment by mikelustosa** [comment]
Resolvido na versão 3.5.1.0

**Comment by rodrigo-ogioni** [comment]
Bom dia Mike,
Atualizei agora para a versão 3.5.1.0 e parou de enviar mensagens. Mesmo no Demo. Agora não envia mais mensagem alguma.
Grato

**Comment by mikelustosa** [comment]
Por favor envie mais detalhes:

Versão do app whatsapp:
Versão do whatsapp web:
Versão do CEF:
Versão do TInject:

**Comment by rodrigo-ogioni** [comment]
Versão do app whatsapp: 2.2238.7
Versão do whatsapp web:   2.2241.7
Versão do CEF: 3.3202.1683.gb095524   (peguei no arquivo README.md) não sei se é isso
Versão do TInject: 3.5.1.0

Grato

**Comment by danielsantb** [comment]
Mesmo aqui

Versão do SO Mobile: Android
Versão do app whatsapp: 2.22.22.80 (Bussines)
Versão do whatsapp web: 2.2240.7
Versão do CEF: Não achei
Versão do TInject: 3.5.1.0

**Comment by rodrigo-ogioni** [comment]
alguma novidade?

**Comment by mikelustosa** [comment]
Atualize para a versão 3.6.0.0

**Comment by rodrigo-ogioni** [comment]
depois que atualizei, passou a dar erro aqui

![image](https://user-images.githubusercontent.com/64044584/199751870-4311137a-1912-46cd-b781-a1d706ed07ce.png)
