### ISSUE TITLE
A database error occurred on your browser

### ISSUE THREAD

**Issue by CaioAlexandre743** [mikelustosa/Projeto-TInject#48]
Acontece com frequência, ao autenticar a sessão, a seguinte situação:
Utilizando com parametrização de login desktop (QrCode), o processo fica preso e abre várias janelas no navegador com o seguinte endereço: https://faq.whatsapp.com/5628289293853417/?locale=en_US

Gostaria de poder, quando retornar esta situação, de encerrar e iniciar novamente.

**Comment by mikelustosa** [comment]
Esse problema foi corrigido nas versões mais recentes do whatsapp. Atualize o aplicativo no celular e sincronize novamente com o TInject.
