### ISSUE TITLE
Uma forma de verificar a versão do whatsapp web que está conectado

### ISSUE THREAD

**Issue by backsubzero** [mikelustosa/Projeto-TInject#50]
Seria interessante uma forma de se verificar a versão do whatsapp web conectado por comando, assim seria mais simples de verificar problemas e reportar falhas.

Aproveitando, o mesmo deveria ser para o CEF, verificar a versão do CEF em operação por comando, hoje eu verifico a versão do js.abr para tentar pegar se teve ou não mudanças.

a ideia é melhorar o report de falhas com dados abaixo:

Versão do app whatsapp:
Versão do whatsapp web:
Versão do CEF:
Versão do TInject:
Versão do JS.abr: 
Versão do Windows:

**Comment by mikelustosa** [comment]
Criado templates issues! Obg!
