### ISSUE TITLE
não envia mensagens

### ISSUE THREAD

**Issue by Piussi** [mikelustosa/Projeto-TInject#52]
ate o dia 01/11 conseguia enviar mensagens, mas sem compilar nada não envia mais a mensagem, apos a atualização de js.abr

 - OS: [e.g. iOS] win32  windows 10
 - CEF Version [e.g. 73] 91.1.22.0
 - WhatsApp web Version [e.g. 22]
 - js.abr file version [e.g. 1.4.0.0]1.5.0.0

tinjectconf.ini do proprio tinject demo
[Informacao]
Aplicativo vinculado=D:\Projetos\TINJECT\Win32\Release\TInject.exe
Valor True=1
Valor False=0
[Path Defines]
FrameWork=
Binary=D:\Projetos\TINJECT\Win32\Release\
Locales=D:\Projetos\TINJECT\Win32\Release\locales
Cache=D:\Projetos\TINJECT\Win32\Release\cache
Data User=D:\Projetos\TINJECT\Win32\Release\User Data
Log File=D:\Projetos\TINJECT\Win32\Release\
Log Console=D:\Projetos\TINJECT\Win32\Release\LogTinject\
GPU=1
Log Severity=0
Log Console Active=0
Auto Receiver attached Path=D:\Projetos\TINJECT\Win32\Release\
Auto Receiver attached=0
[Tinject Comp]
TInject Versão=3.5.0.0
Caminho JS=https://raw.githubusercontent.com/mikelustosa/Projeto-TInject/master/Source/JS/js.abr
CEF4 Versão=91.1.22.0
CHROME Versão=91.0.4472.124
Dlls=libcef.dll / chrome_elf.dll
Ultima interação=03/11/22 22:21:14

**Comment by mikelustosa** [comment]
#51
