### ISSUE TITLE
checkNumberStatus is not working 

### ISSUE THREAD

**Issue by sergey-chechaev** [mikelustosa/Projeto-TInject#53]
**Describe the bug**
Function checkNumberStatus is not working 

**To Reproduce**
1. Inject script
2. execute checkNumberStatus

**Expected behavior**
Must return 
`"status" => true`

**But return:**

```
status
: 
TypeError: Cannot read properties of undefined (reading 'queryPhoneExists') at window.WAPI.checkNumberStatus (<anonymous>:2015:56) at <anonymous>:1:6
message
: 
"Cannot read properties of undefined (reading 'queryPhoneExists')"
stack
: 
"TypeError: Cannot read properties of undefined (reading 'queryPhoneExists')\n    at window.WAPI.checkNumberStatus (<anonymous>:2015:56)\n    at <anonymous>:1:6"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4598042/202421154-4334d5c8-92bd-448c-9647-f1792919eee0.png)

**Whatsapp WEB version:  2.2244.6**

**Comment by sergey-chechaev** [comment]
Solved. You need use exist code 910 instead "+"

**Comment by ono77** [comment]
hi Sergey, I also have the same problem
What do you mean about 'use exist code 910 instead "+"
I used
window.WAPI.checkNumberStatus('XX3333333333')   where XX is country code without "+"

**Comment by sergey-chechaev** [comment]
> hi Sergey, I also have the same problem What do you mean about 'use exist code 910 instead "+" I used window.WAPI.checkNumberStatus('XX3333333333') where XX is country code without "+"

You need use exit code + country code fore example "+79263456789" -> "81079263456789"

**Comment by ono77** [comment]
> exit code + country
thank you, it's strange that my case it works only if I use numbers without exit code and without country code:
WAPI.checkNumberStatus('2634567890') -> true
WAPI.checkNumberStatus('00392634567890') -> false   (for Italy exit code=00 and country code=39)

**Comment by sergey-chechaev** [comment]
> > exit code + country
> 
> thank you, it's strange that in my case it works only if I use numbers without exit code and without country code: WAPI.checkNumberStatus('2634567890') -> true WAPI.checkNumberStatus('00392634567890') -> false (for Italy exit code=00 and country code=39)

Is It work `WAPI.checkNumberStatus('810392634567890')`? I don't know why but for USA number exit code `810` works

**Comment by Zer0bytte** [comment]
> 

Have you fixed the problem?

**Comment by ono77** [comment]
> Is It work `WAPI.checkNumberStatus('810392634567890')`?

I already tried and not working.
