### ISSUE TITLE
Retorna como Connected, apesar de não estar.

### ISSUE THREAD

**Issue by leoguitar2006** [mikelustosa/Projeto-TInject#54]
Estou enfrentando um problema faz um certo e não consegui contornar.

Uso o QrCode do tipo Ft_None e faço a autenticação normalmente.
Após isso, se eu fechar a aplicação, desconectar a sessão do chrome do celular, e reiniciar a aplicação, o TInject me devolve o status Server_Connected, apesar de eu já ter feito a desconexão no celular.

De maneira resumida:

1. Autenticar usando QrCode Ft_None;
2. Fechar a aplicação
3. Desconectar do celular
4. Abrir a aplicação
5. Ocorre o problema de me dar como connected.

Se eu fecho a aplicação novamente e abro, aí ele me retorna certo. Isso ocorre no DEMO também.

Depurando, me parece que o problema pode estar no OnTitleChange do Chromium, no FrmConsole, mas não consegui avançar.

**Comment by mikelustosa** [comment]
> Estou enfrentando um problema faz um certo e não consegui contornar.
> 
> Uso o QrCode do tipo Ft_None e faço a autenticação normalmente. Após isso, se eu fechar a aplicação, desconectar a sessão do chrome do celular, e reiniciar a aplicação, o TInject me devolve o status Server_Connected, apesar de eu já ter feito a desconexão no celular.
> 
> De maneira resumida:
> 
> 1. Autenticar usando QrCode Ft_None;
> 2. Fechar a aplicação
> 3. Desconectar do celular
> 4. Abrir a aplicação
> 5. Ocorre o problema de me dar como connected.
> 
> Se eu fecho a aplicação novamente e abro, aí ele me retorna certo. Isso ocorre no DEMO também.
> 
> Depurando, me parece que o problema pode estar no OnTitleChange do Chromium, no FrmConsole, mas não consegui avançar.

Corrigido na versão atual
