### ISSUE TITLE
Checknumberstatus multi errors !

### ISSUE THREAD

**Issue by Zer0bytte** [mikelustosa/Projeto-TInject#57]
English:
I'm trying to use checknumberstatus function in this format --> exitcode+country code + phone number
give me these two different errors while trying two different country numbers

PORTUGUESE:
Estou tentando usar a função checknumberstatus neste formato --> código de saída+código do país + número de telefone
dê-me esses dois erros diferentes ao tentar dois números de países diferentes

![image](https://user-images.githubusercontent.com/85482481/202985631-10c241ab-a115-470c-8e9d-b9b2401f69ea.png)

**Comment by ono77** [comment]
same to me, it's not working

**Comment by rajeshshettysrs** [comment]
same here for me also,please help

**Comment by mikelustosa** [comment]
> English: I'm trying to use checknumberstatus function in this format --> exitcode+country code + phone number give me these two different errors while trying two different country numbers
> 
> PORTUGUESE: Estou tentando usar a função checknumberstatus neste formato --> código de saída+código do país + número de telefone dê-me esses dois erros diferentes ao tentar dois números de países diferentes
> 
> ![image](https://user-images.githubusercontent.com/85482481/202985631-10c241ab-a115-470c-8e9d-b9b2401f69ea.png)

Inclua @c.us no final do número. Ex 558199301443@c.us

**Comment by rajeshshettysrs** [comment]
Checknumberstatus is not working sir,its not returning status of the mobile number,please help

**Comment by rajeshshettysrs** [comment]
> Checknumberstatus is not working sir,its not returning status of the mobile number,please help

Checknumberstatus não está funcionando senhor, não está retornando o status do número do celular, por favor me ajude
