### ISSUE TITLE
Erro Dll

### ISSUE THREAD

**Issue by sorrilhaale** [mikelustosa/Projeto-TInject#58]
Olá amigos; Instalei o CEF4 no Delphi 10.4 e tenho problemas com dll. Por favor, podem me auxiliar. Grato pela atenção
![erro](https://user-images.githubusercontent.com/49649642/206220249-494d965a-c815-4e7c-9e4e-5e8773780252.png)

**Comment by mikelustosa** [comment]
> Olá amigos; Instalei o CEF4 no Delphi 10.4 e tenho problemas com dll. Por favor, podem me auxiliar. Grato pela atenção ![erro](https://user-images.githubusercontent.com/49649642/206220249-494d965a-c815-4e7c-9e4e-5e8773780252.png)

Basta seguir o tutorial de instalação
