### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by thiagoamaralcaragua** [mikelustosa/Projeto-TInject#61]
boa tarde, quando tento usar so da erro de sem comunicação com servidor
ja baixei os e compilei e o erro persistema

**Comment by thiagoamaralcaragua** [comment]
tem versao mais nova que a v3.8.2.0 que e a atual que tenho?

**Comment by mikelustosa** [comment]
Provavelmente deve ser mau instalação. Tente https://www.youtube.com/watch?v=6WR2Gberp5s&t=61s
