### ISSUE TITLE
Problema na variavel "isME'

### ISSUE THREAD

**Issue by danielsantb** [mikelustosa/Projeto-TInject#64]
Aparentemente a variavel "isME" não esta rertornando o valor correto, varios relatos de varios clientes.

Assim que tiver mais informações posto aqui.

**Comment by mikelustosa** [comment]
Será resolvido na próxima release.

**Comment by danielsantb** [comment]
Workround para quem estiver com problema, cadastrar o numero do cliente que esta com o bot configurado e verificar se o numero vem na variarel AMessage.from no Demo.

**Comment by mikelustosa** [comment]
Fix [](https://github.com/mikelustosa/Projeto-TInject/commit/2dd09290139dbf37f8d4a3ef557a8fb5cd88d2c8)

**Comment by mikelustosa** [comment]
[Fix](https://github.com/mikelustosa/Projeto-TInject/commit/2dd09290139dbf37f8d4a3ef557a8fb5cd88d2c8)
