### ISSUE TITLE
SendImage issue

### ISSUE THREAD

**Issue by ono77** [mikelustosa/Projeto-TInject#66]
In the last version of WA  2.2340.9, the function SendImage is not working

![sendimage](https://github.com/mikelustosa/Projeto-TInject/assets/95230220/f28f8300-776b-425c-b8f1-30a64b0164c1)

**Comment by rajeshshettysrs** [comment]
we are also facing same issue. Please help

**Comment by mikelustosa** [comment]
Fix https://github.com/mikelustosa/Projeto-TInject/commit/f7b569f725f4ed3541d797dbe8f8f8eb847d90e9

**Comment by rajeshshettysrs** [comment]
> Fix [f7b569f](https://github.com/mikelustosa/Projeto-TInject/commit/f7b569f725f4ed3541d797dbe8f8f8eb847d90e9)

Sir getting same error as Getting error as Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isNewsletter')
    at t.getMaxNumberSelectableMedia (app.f8ceec360734d3a1abb3.js:51:662539)
    at app.f8ceec360734d3a1abb3.js:96:851568
    at Generator.next (<anonymous>)
    at t (vendor1~app.7f14216f970118f62a35.js:2:66483)
    at s (vendor1~app.7f14216f970118f62a35.js:2:66694)
    at vendor1~app.7f14216f970118f62a35.js:2:66753
    at new Promise (<anonymous>)
    at vendor1~app.7f14216f970118f62a35.js:2:66634
    at M.processAttachments (app.f8ceec360734d3a1abb3.js:96:852098)
    at eval (eval at executeScript (web.whatsapp.com/:369:16), <anonymous>:1582:16)

**Comment by rajeshshettysrs** [comment]
> Fix [f7b569f](https://github.com/mikelustosa/Projeto-TInject/commit/f7b569f725f4ed3541d797dbe8f8f8eb847d90e9)
Sir document is attaching to chat,but not sending,please help
![image](https://github.com/mikelustosa/Projeto-TInject/assets/20316958/11e10645-02bc-48fb-9bea-e4eda3806925)

**Comment by mikelustosa** [comment]
Basta atualizar o Tinject.
