### ISSUE TITLE
Uncaught ReferenceError: webpackChunkwhatsapp_web_client is not defined

### ISSUE THREAD

**Issue by Zer0bytte** [mikelustosa/Projeto-TInject#70]
Uncaught ReferenceError: webpackChunkwhatsapp_web_client is not defined

**Comment by mikelustosa** [comment]
Version whatsapp?

**Comment by Zer0bytte** [comment]
> Version whatsapp?

latest version : 2.2409.4

**Comment by mikelustosa** [comment]
Update to 2.24.4.xx

**Comment by Zer0bytte** [comment]
> Update to 2.24.4.xx

how to do it?

**Comment by Zer0bytte** [comment]
> Update to 2.24.4.xx

im injecting wapi.js into the browser

**Comment by mikelustosa** [comment]
I tested on version 2.2409.2 of WhatsApp web. And it's working normally.

**Comment by mikelustosa** [comment]
I'll wait to update to the same version as yours

**Comment by frankdors** [comment]
See info about:
https://github.com/pedroslopez/whatsapp-web.js/issues/2789#issuecomment-1972768458

**Comment by mikelustosa** [comment]
Tested on WhatsApp web version 2.2410.1 TInject working perfectly. Wait for this version to arrive. If you have another solution, please be sure to open another issue.
