### ISSUE TITLE
The system does not send messages

### ISSUE THREAD

**Issue by rodrigo-ogioni** [mikelustosa/Projeto-TInject#74]
Good morning!
In the system, some customers always complain that messages are not being sent. Then I go in there and everything is connected. So I have to log out and ask the client to log in again, but after a while I have to do this process again. Any tips to prevent this problem from happening?

**Comment by mikelustosa** [comment]
WhatsApp with instability. Just wait.

**Comment by rodrigo-ogioni** [comment]
> WhatsApp with instability. Just wait.

I understand, this problem is not just yesterday, it has been happening for several months...
