### ISSUE TITLE
Whatsapp is not sending messages

### ISSUE THREAD

**Issue by rodrigo-ogioni** [mikelustosa/Projeto-TInject#75]
Good morning, since yesterday, tinject is no longer sending messages via WhatsApp, this is a general problem, is everyone experiencing this?

**Comment by mikelustosa** [comment]
> Good morning, since yesterday, tinject is no longer sending messages via WhatsApp, this is a general problem, is everyone experiencing this?

Yes. There is a bug in WhatsApp web. Problem: After authenticating, a reload is automatically performed. Solution: After this reload, restart your application.
