### ISSUE TITLE
error sending message

### ISSUE THREAD

**Issue by rodrigo-ogioni** [mikelustosa/Projeto-TInject#76]
I disconnect, connect, close the application, open it again, nothing works

**Comment by mikelustosa** [comment]
Just restart after the first authentication. This will solve it. It's just instability in your region.

**Comment by jesussales** [comment]
the problem continue, in my case from Spain the error is


UjcTej1zGTO.js?_nc_x=Ij3Wp8lg5Kz:1532 Uncaught TypeError: this.findImpl is not a function
    at b.<anonymous> (UjcTej1zGTO.js?_nc_x=Ij3Wp8lg5Kz:1531:5481)
    at Generator.next (<anonymous>)
    at h (_iGJBfP7INJ.js?_nc_x=Ij3Wp8lg5Kz:11:125)
    at g (_iGJBfP7INJ.js?_nc_x=Ij3Wp8lg5Kz:11:349)
    at _iGJBfP7INJ.js?_nc_x=Ij3Wp8lg5Kz:11:408
    at new Promise (<anonymous>)
    at b._serverQuery (_iGJBfP7INJ.js?_nc_x=Ij3Wp8lg5Kz:11:277)
    at f._query (UjcTej1zGTO.js?_nc_x=Ij3Wp8lg5Kz:1531:4997)
    at f.find (UjcTej1zGTO.js?_nc_x=Ij3Wp8lg5Kz:1531:3243)
    at <anonymous>:3:40

**Comment by jesussales** [comment]
here's my temporary solution until we find a better one it's still under testing, but hoping to work its basically overwriting Store.Chat.find to make sure the new chat is in store and avoiding to call findImpl

if (!window.Store.Chat.findTemp) {
    window.Store.Chat.findTemp = window.Store.Chat.find;
}
window.Store.Chat.find = async function (id) {
    try {
        return await window.Store.Chat.findTemp(id);
    }
    catch (err) {
        if (err && err.message && err.message.includes('findImpl')) {
            var tempChat = new window.Store.Chat.modelClass({ id });
            window.Store.Chat.add(tempChat);
            return await window.Store.Chat.findTemp(id);
        }
        throw err;
    }
};
this is me using my custom version of WAPI
