### ISSUE TITLE
javascript exception

### ISSUE THREAD

**Issue by NirLevi001** [mikelustosa/Projeto-TInject#77]
it seems that something has changed in whatsapp web .
I get exceptions and currently it doesnt read new messages and doesnt get delivered notifications .
 
![screen1](https://github.com/mikelustosa/Projeto-TInject/assets/8735048/21915734-cfcb-4fac-b9c3-31cdc118a118)
![screen2](https://github.com/mikelustosa/Projeto-TInject/assets/8735048/f9f25bd3-9f78-48f8-869e-d3d678c1f80c)

**Comment by WSSamuel2** [comment]
Para resolver o problema por enquanto coloque um Timer no formulário .

![Screenshot_1](https://github.com/mikelustosa/Projeto-TInject/assets/168032168/403fb8dd-4f20-4ab6-a86c-9e0cc8d03517)
![Screenshot_2](https://github.com/mikelustosa/Projeto-TInject/assets/168032168/80ef7827-2eca-4480-8ed5-98796e655b82)

**Comment by NirLevi001** [comment]
It used to work with events (OnNewMessage ,OnDelivered) .
why change it to timer driven?

**Comment by mikelustosa** [comment]
[fix](https://github.com/mikelustosa/Projeto-TInject/commit/6f6686102241acaecab7a950317dba4e49e88a38)
