### ISSUE TITLE
The function IsLoggedIn not working for Whatsapp Web 2.3000.1013

### ISSUE THREAD

**Issue by sergey-chechaev** [mikelustosa/Projeto-TInject#78]
## Description

The function IsLoggedIn not working for Whatsapp Web 2.3000.1013005935

`window.Store.Contact.checksum` is undefined

https://github.com/mikelustosa/Projeto-TInject/blob/6f6686102241acaecab7a950317dba4e49e88a38/Source/JS/js.abr#L1191

## Environment

- **Browser:** Chrome 123.0
- not working for Whatsapp Web 2.3000.1013005935

## Steps to Reproduce

Insert WAPI js in Browser console and execute `WAPI.isLoggedIn` function

For Whatsapp Web 2.3000.10129
![image](https://github.com/orkestral/venom/assets/4598042/9670384b-735a-441f-8ed8-c616e9419178)

For Whatsapp Web 2.3000.10130
![image](https://github.com/orkestral/venom/assets/4598042/bd9980e3-60c8-4b6c-b680-161726f652ce)

**Comment by mikelustosa** [comment]
Fiz #77

**Comment by sergey-chechaev** [comment]
This solution is not working
