### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by jesussales** [mikelustosa/Projeto-TInject#79]
Are there any method to send data to channel?

**Comment by mikelustosa** [comment]
> Are there any method to send data to channel?

No

**Comment by jesussales** [comment]
Ok, of Itry to send like chat, the message send and state facilite, if Click in the emergency Ivón and resend, send It to channel, are there function to resend chat with the WhatsAppId Message?

i think this option can a method…. Are you think implement en y mode to send Message to channel?
