### ISSUE TITLE
WAPI.sendMessageToID not working

### ISSUE THREAD

**Issue by ono77** [mikelustosa/Projeto-TInject#81]
WAPI.sendMessageToID('number@c.us','test')

gives this error:

VM60:1804 Uncaught TypeError: Cannot read properties of undefined (reading 'findChat')
    at window.WAPI.sendMessageToID (<anonymous>:1804:34)
    at <anonymous>:1:6

**Comment by sergey-chechaev** [comment]
So you need to change `findChat` to `findOrCreateLatestChat`

Fix, change 

`conditions: (module) => (module && module.findChat) ? module : null`

to

`conditions: (module) => (module && module.findOrCreateLatestChat) ? module : null`

And then use `chat = Store.FindChat.findOrCreateLatestChat(idUser)`

**Comment by danielsantb** [comment]
Same here, this fix dont work!

**Comment by mikelustosa** [comment]
Fix js.abr v.3.0.2.0
