### ISSUE TITLE
Instalando o Pacote

### ISSUE THREAD

**Issue by VanessaeaBatista** [mikelustosa/Projeto-TInject#84]
Ao instalar diretamente o pacote, Delphi Alexandria,
apresenta essa mensagem 
[dcc32 Error] uTInject.ConfigCEF.pas(232): E2003 Undeclared identifier: 'UserDataPath'

Instalando via exe
Copyright (c) 1983,2022 Embarcadero Technologies, Inc.
C:\DelphiAlexandria\TInject\Projeto-TInject-master\Source\Services\uTInject.ConfigCEF.pas(232) Error: E2003 Undeclared identifier: 'UserDataPath'
C:\DelphiAlexandria\TInject\Projeto-TInject-master\Source\Services\uTInject.ConfigCEF.pas(389) Error: E2003 Undeclared identifier: 'UserDataPath'
C:\DelphiAlexandria\TInject\Projeto-TInject-master\Source\Services\uTInject.ConfigCEF.pas(400) Error: E2003 Undeclared identifier: 'UserDataPath'
C:\DelphiAlexandria\TInject\Projeto-TInject-master\Source\View\uTInject.FrmQRCode.pas(67) Fatal: F2063 Could not compile used unit 'uTInject.ConfigCEF.pas'
Compilation failure

**Comment by mikelustosa** [comment]
Esse problema é devido ao CEF. Instale a versão do CEF que vem junto ao TInject e não terá problemas.
