### ISSUE TITLE
Erro no demo

### ISSUE THREAD

**Issue by VanessaeaBatista** [mikelustosa/Projeto-TInject#85]
os componentes CEF e TInject estão instalados.

Fui abrir o demo
e aparece a seguinte mensagem

[dcc32 Error] uTInject.Console.pas(1505): E2010 Incompatible types: 'TCefLogSeverity' and 'Cardinal'
Chromium1.OnConsoleMessage        := Chromium1ConsoleMessage;

**Comment by mikelustosa** [comment]
É a versão do CEF incompatível. Use a versão que vem junto ao github do TInject, e não terá problemas.

**Comment by mikelustosa** [comment]
> Chromium1.OnConsoleMessage := Chromium1ConsoleMessage;

Try 

Chromium1.OnConsoleMessage := Chromium1.onConsoleMessage;
