### ISSUE TITLE
WhatsApp Business

### ISSUE THREAD

**Issue by aleriopreto2012** [mikelustosa/Projeto-TInject#9]
Ao iniciar a aplicação e caputar a lista de contatos nao retorna do whatsapp business, oque pode ser?
no whastapp normal retorna normalmente..

**Comment by mikelustosa** [comment]
> Ao iniciar a aplicação e caputar a lista de contatos nao retorna do whatsapp business, oque pode ser?
> no whastapp normal retorna normalmente..

Veja: http://www.tinject.com.br/viewtopic.php?f=4&t=8&sid=b320b54e1495915c1450c52883afca1e
